export const PACKING_TEMPLATE: { category: string; items: string[] }[] = [
  {
    category: 'Safety & First Aid',
    items: [
      'Band aids',
      'Disinfectant',
      'Gauze',
      'Antiseptic cream',
      'Petroleum jelly',
      'Pain killers',
      'Antihistamine',
      'Nausea tablets',
      'Upset stomach tablets',
      'Emergency blanket',
      'Fire extinguisher',
      'Medical aid cards',
      'Prescription medicine',
      'Driver\'s licence',
      'Identification documents',
    ],
  },
  {
    category: 'Tent & Shelter',
    items: [
      'Tent & bag',
      'Ground sheet',
      'Rubber mallet & tent pegs',
      'Tent repair kit',
      'Windbreaker',
      'Gazebo',
      'Nylon rope',
      'Storm straps',
      'Tent / seam sealant',
    ],
  },
  {
    category: 'Sleeping & Softs',
    items: [
      'Sleeping bags & liner',
      'Pillows',
      'Sheets',
      'Thermal blanket',
      'Air mattress & bag',
      'Foam mattress',
      'Mosquito nets',
    ],
  },
  {
    category: 'Kitchen & Cooking',
    items: [
      'Gas braai / cooker',
      'Gas cylinder (full)',
      'Pots',
      'Frying pan',
      'Braai tongs & grid',
      'Lighter & firelighters',
      'Wood / charcoal',
      'Cutting board',
      'Knives, forks & spoons',
      'Plates & bowls',
      'Mugs & glasses',
      'Can opener',
      'Bottle opener',
      'Dish detergent',
      'Dish towels',
      'Aluminium foil',
      'Zip sealer bags',
      'Oven mitts',
      'Salt & pepper',
      'Cooking oil',
      'Water container',
    ],
  },
  {
    category: 'Food & Drinks',
    items: [
      'Canned meats & tuna',
      'Canned vegetables',
      'Fresh vegetables',
      'Bread & spreads',
      'Pasta or rice',
      'Coffee',
      'Tea',
      'Sugar',
      'Milk (long life)',
      'Butter',
      'Spices',
      'Snacks & energy bars',
      'Bottled water',
      'Fresh fruit juices',
    ],
  },
  {
    category: 'Refrigeration',
    items: [
      'Cooler bag / fridge',
      'Ice bricks',
      'Thermal jug',
    ],
  },
  {
    category: 'Hygiene',
    items: [
      'Toilet paper',
      'Biodegradable soap',
      'Shampoo & conditioner',
      'Toothbrush & toothpaste',
      'Towels',
      'Swimming towels',
      'Sunscreen',
      'Insect repellent',
      'Disposable razors',
      'Shower tent',
      'Portable toilet',
    ],
  },
  {
    category: 'Clothing',
    items: [
      'Casual clothing',
      'Swim wear',
      'Sleepwear',
      'Hat',
      'Beanie',
      'Hiking boots',
      'Sandals',
      'Waterproof jacket',
      'Thermal jacket',
    ],
  },
  {
    category: 'Lighting & Power',
    items: [
      'Torch & batteries',
      'Lanterns & fuel',
      'Power extension cord',
      'Phone & device chargers',
      'Portable power bank',
    ],
  },
  {
    category: 'Tools & Extras',
    items: [
      'Multi-purpose knife',
      'Hammer',
      'Screwdrivers',
      'Cable ties',
      'Duct tape',
      'Warning triangles',
      'Spare tyre',
      'Wheel spanner & jack',
      'Refuse bags',
      'Clothesline & pegs',
      'Washing powder',
    ],
  },
];
